export type AuditEvidenceKind = "Primary experiment" | "Supporting experiment" | "Benchmark only" | "Context only";
export type AuditUse = "Calculator benchmark" | "Treatment benchmark" | "Feature evidence" | "Context only" | "Do not pool";

export type AuditRow = {
  conditionId: string;
  paperRecord: string;
  sourceFile: string;
  evidenceKind: AuditEvidenceKind;
  access: "Public" | "Private reviewed" | "Public metadata only";
  microbe: string;
  strainOrCommunity: string;
  anode: string;
  cathode: string;
  reactor: string;
  anodeVolumeMl: number | null;
  membrane: string;
  substrate: string;
  substrateConcentrationG_L: number | null;
  salinityG_L: number | null;
  conductivityMsCm: number | null;
  temperatureC: number | null;
  ph: number | null;
  externalResistanceOhm: number | null;
  voltageV: number | null;
  voltageUncertaintyV: number | null;
  openCircuitVoltageV: number | null;
  powerDensityMwM2: number | null;
  powerDensityUncertaintyMwM2: number | null;
  currentDensityMaM2: number | null;
  codRemovalPercent: number | null;
  treatmentRate: string;
  sourceLocator: string;
  use: AuditUse;
  qualityFlag: string;
};

/**
 * Condition-level records extracted from the supplied papers. Null means the
 * paper did not report the field in a comparable form. Numeric values are the
 * reported central values; uncertainty is kept in a separate column.
 */
export const auditRows: AuditRow[] = [
  {
    conditionId: "BV-LIT-009-G-100",
    paperRecord: "BV-LIT-009",
    sourceFile: "PDF 1.pdf",
    evidenceKind: "Primary experiment",
    access: "Public",
    microbe: "Pseudomonas aeruginosa",
    strainOrCommunity: "Mesophilic, non-fermentative isolate; strain not specified",
    anode: "Carbon cloth, 3 x 5 cm",
    cathode: "Carbon cloth, 3 x 5 cm; potassium permanganate catholyte",
    reactor: "Double chamber; two 500 mL bottles; 300 mL working volume",
    anodeVolumeMl: 300,
    membrane: "Nafion 115, 25 cm2 chamber",
    substrate: "Glucose",
    substrateConcentrationG_L: 3,
    salinityG_L: null,
    conductivityMsCm: null,
    temperatureC: null,
    ph: 7,
    externalResistanceOhm: 100,
    voltageV: 0.202,
    voltageUncertaintyV: null,
    openCircuitVoltageV: null,
    powerDensityMwM2: 136,
    powerDensityUncertaintyMwM2: 87,
    currentDensityMaM2: 673,
    codRemovalPercent: 88.5,
    treatmentRate: "",
    sourceLocator: "PDF 1, pp. 3-5; Fig. 2; Table 1",
    use: "Calculator benchmark",
    qualityFlag: "Reported voltage, current density and power density do not reconcile cleanly with a simple V/R/area calculation. Preserve as reported and do not use as a deterministic training row.",
  },
  {
    conditionId: "BV-LIT-009-F-100",
    paperRecord: "BV-LIT-009",
    sourceFile: "PDF 1.pdf",
    evidenceKind: "Primary experiment",
    access: "Public",
    microbe: "Pseudomonas aeruginosa",
    strainOrCommunity: "Mesophilic, non-fermentative isolate; strain not specified",
    anode: "Carbon cloth, 3 x 5 cm",
    cathode: "Carbon cloth, 3 x 5 cm; potassium permanganate catholyte",
    reactor: "Double chamber; two 500 mL bottles; 300 mL working volume",
    anodeVolumeMl: 300,
    membrane: "Nafion 115, 25 cm2 chamber",
    substrate: "Fructose",
    substrateConcentrationG_L: 3,
    salinityG_L: null,
    conductivityMsCm: null,
    temperatureC: null,
    ph: 7,
    externalResistanceOhm: 100,
    voltageV: 0.033,
    voltageUncertaintyV: null,
    openCircuitVoltageV: null,
    powerDensityMwM2: 3.6,
    powerDensityUncertaintyMwM2: 1.6,
    currentDensityMaM2: 100,
    codRemovalPercent: 67.5,
    treatmentRate: "",
    sourceLocator: "PDF 1, p. 5; Fig. 3; Table 1",
    use: "Calculator benchmark",
    qualityFlag: "Duplicate batch tests; maximum voltage is reported at 3 g/L, while higher concentrations show inhibition.",
  },
  {
    conditionId: "BV-LIT-009-S-100",
    paperRecord: "BV-LIT-009",
    sourceFile: "PDF 1.pdf",
    evidenceKind: "Primary experiment",
    access: "Public",
    microbe: "Pseudomonas aeruginosa",
    strainOrCommunity: "Mesophilic, non-fermentative isolate; strain not specified",
    anode: "Carbon cloth, 3 x 5 cm",
    cathode: "Carbon cloth, 3 x 5 cm; potassium permanganate catholyte",
    reactor: "Double chamber; two 500 mL bottles; 300 mL working volume",
    anodeVolumeMl: 300,
    membrane: "Nafion 115, 25 cm2 chamber",
    substrate: "Sucrose",
    substrateConcentrationG_L: 4,
    salinityG_L: null,
    conductivityMsCm: null,
    temperatureC: null,
    ph: 7,
    externalResistanceOhm: 100,
    voltageV: 0.079,
    voltageUncertaintyV: null,
    openCircuitVoltageV: null,
    powerDensityMwM2: 20.8,
    powerDensityUncertaintyMwM2: null,
    currentDensityMaM2: 0.26,
    codRemovalPercent: 54.2,
    treatmentRate: "",
    sourceLocator: "PDF 1, p. 5; Fig. 4; Table 1",
    use: "Calculator benchmark",
    qualityFlag: "The paper reports a current-density value that conflicts with the voltage/resistance/area context. Retain the warning and do not pool without rechecking the original figure.",
  },
  {
    conditionId: "BV-LIT-009-G-PMAX",
    paperRecord: "BV-LIT-009",
    sourceFile: "PDF 1.pdf",
    evidenceKind: "Primary experiment",
    access: "Public",
    microbe: "Pseudomonas aeruginosa",
    strainOrCommunity: "21-day anodic biofilm",
    anode: "Carbon cloth, 3 x 5 cm",
    cathode: "Carbon cloth; potassium permanganate catholyte",
    reactor: "Double chamber polarization series",
    anodeVolumeMl: 300,
    membrane: "Nafion 115",
    substrate: "Glucose",
    substrateConcentrationG_L: 3,
    salinityG_L: null,
    conductivityMsCm: null,
    temperatureC: null,
    ph: 7,
    externalResistanceOhm: 1000,
    voltageV: 0.77,
    voltageUncertaintyV: null,
    openCircuitVoltageV: null,
    powerDensityMwM2: 213,
    powerDensityUncertaintyMwM2: null,
    currentDensityMaM2: null,
    codRemovalPercent: null,
    treatmentRate: "",
    sourceLocator: "PDF 1, p. 5; Fig. 5A",
    use: "Do not pool",
    qualityFlag: "Polarization value and reported voltage/area imply a normalization inconsistency. Keep as a paper-level benchmark only.",
  },
  {
    conditionId: "BV-LIT-011-20",
    paperRecord: "BV-LIT-011",
    sourceFile: "PDF 2.pdf",
    evidenceKind: "Primary experiment",
    access: "Public",
    microbe: "Halophilic exoelectrogenic enrichment",
    strainOrCommunity: "Arabian Sea inoculum; enriched community",
    anode: "316L stainless-steel mesh, 3 x 3 cm",
    cathode: "Carbon felt, 3 x 3 x 0.55 cm; reported area 18.6 x 10^-4 m2",
    reactor: "Dual chamber; 100 mL anode and 100 mL cathode",
    anodeVolumeMl: 100,
    membrane: "Nafion 117",
    substrate: "Sodium acetate",
    substrateConcentrationG_L: 3.5,
    salinityG_L: 20,
    conductivityMsCm: 49,
    temperatureC: 37,
    ph: 7,
    externalResistanceOhm: 100,
    voltageV: 0.240,
    voltageUncertaintyV: 0.008,
    openCircuitVoltageV: 0.435,
    powerDensityMwM2: 96.77,
    powerDensityUncertaintyMwM2: 3,
    currentDensityMaM2: 1908.6,
    codRemovalPercent: 76,
    treatmentRate: "550 mg COD/L/day; coulombic efficiency 12 +/- 0.06%",
    sourceLocator: "PDF 2, pp. 3, 6, 9; Table 2; Fig. 3",
    use: "Calculator benchmark",
    qualityFlag: "Power-density normalization uses projected cathode area; current-density maximum is reported at 5 ohm while peak power is at 100 ohm.",
  },
  {
    conditionId: "BV-LIT-011-40",
    paperRecord: "BV-LIT-011",
    sourceFile: "PDF 2.pdf",
    evidenceKind: "Primary experiment",
    access: "Public",
    microbe: "Halophilic exoelectrogenic enrichment",
    strainOrCommunity: "Arabian Sea inoculum; enriched community",
    anode: "316L stainless-steel mesh, 3 x 3 cm",
    cathode: "Carbon felt, 3 x 3 x 0.55 cm; reported area 18.6 x 10^-4 m2",
    reactor: "Dual chamber; 100 mL anode and 100 mL cathode",
    anodeVolumeMl: 100,
    membrane: "Nafion 117",
    substrate: "Sodium acetate",
    substrateConcentrationG_L: 3.5,
    salinityG_L: 40,
    conductivityMsCm: 82,
    temperatureC: 37,
    ph: 7,
    externalResistanceOhm: 100,
    voltageV: 0.374,
    voltageUncertaintyV: 0.007,
    openCircuitVoltageV: 0.670,
    powerDensityMwM2: 162.09,
    powerDensityUncertaintyMwM2: 3,
    currentDensityMaM2: 2161.29,
    codRemovalPercent: 83,
    treatmentRate: "625 mg COD/L/day; coulombic efficiency 14 +/- 0.08%",
    sourceLocator: "PDF 2, pp. 3, 6, 9; Table 2; Fig. 3",
    use: "Calculator benchmark",
    qualityFlag: "Power-density normalization uses projected cathode area; current-density maximum is reported at 5 ohm while peak power is at 100 ohm.",
  },
  ...[
    ["500", 27.22, 31.17, 0.060, 0.0055, 0.450, 71.06, 3.1, 1338.14, 1.045, 1.13],
    ["1000", 58.44, 42.78, 0.160, 0.0109, 0.640, 207.05, 5, 2051.28, 1.83, 1.18],
    ["2000", 116.88, 59.67, 0.120, 0.0084, 0.520, 106.25, 4.2, 1722.75, 2.08, 1.29],
    ["3000", 175.32, 74.56, 0.040, 0.0045, 0.430, 48.3, 2.3, 1250, 3.2, 2.26],
  ].map(([mM, salinity, conductivity, voltage, voltageUncertainty, ocv, power, powerUncertainty, current, starchRate, amylase]) => ({
    conditionId: `BV-LIT-010-${mM}`,
    paperRecord: "BV-LIT-010",
    sourceFile: "PDF 11.pdf",
    evidenceKind: "Primary experiment" as AuditEvidenceKind,
    access: "Private reviewed" as const,
    microbe: "Halophilic starch-degrading consortium",
    strainOrCommunity: "Sambhar Lake isolates; Bacillus, Staphylococcus and Virgibacillus groups",
    anode: "Stainless-steel mesh, 5 x 5 cm; reported area 4.929 x 10^-3 m2",
    cathode: "Graphite felt, 3 x 3 x 0.58 cm; reported area 24.96 x 10^-4 m2",
    reactor: "Dual chamber; 100 mL anode and 100 mL cathode",
    anodeVolumeMl: 100,
    membrane: "Nafion 117",
    substrate: "Starch",
    substrateConcentrationG_L: 12,
    salinityG_L: salinity as number,
    conductivityMsCm: conductivity as number,
    temperatureC: null,
    ph: 7,
    externalResistanceOhm: 100,
    voltageV: voltage as number,
    voltageUncertaintyV: voltageUncertainty as number,
    openCircuitVoltageV: ocv as number,
    powerDensityMwM2: power as number,
    powerDensityUncertaintyMwM2: powerUncertainty as number,
    currentDensityMaM2: current as number,
    codRemovalPercent: null,
    treatmentRate: `${starchRate} kg starch/m3/day; amylase ${amylase} IU/mL`,
    sourceLocator: "PDF 11, pp. 3-6; Table 2; Fig. 2",
    use: "Calculator benchmark" as AuditUse,
    qualityFlag: "Private source: do not redistribute the PDF. Paper reports starch as 12 g in the anolyte; verify concentration basis before model use. Peak power and current density refer to different resistance points.",
  })),
  {
    conditionId: "BV-LIT-007-YEAST-AU",
    paperRecord: "BV-LIT-007",
    sourceFile: "Public full text; no local PDF",
    evidenceKind: "Benchmark only",
    access: "Public",
    microbe: "Saccharomyces cerevisiae",
    strainOrCommunity: "Yeast laboratory system",
    anode: "Graphite modified with gold nanoparticles and/or polypyrrole",
    cathode: "Two-electrode laboratory cell; ferricyanide acceptor",
    reactor: "Laboratory electrochemical/MFC test",
    anodeVolumeMl: null,
    membrane: "Not comparable",
    substrate: "Glucose",
    substrateConcentrationG_L: null,
    salinityG_L: null,
    conductivityMsCm: null,
    temperatureC: null,
    ph: null,
    externalResistanceOhm: null,
    voltageV: null,
    voltageUncertaintyV: null,
    openCircuitVoltageV: 0.455,
    powerDensityMwM2: 22.8,
    powerDensityUncertaintyMwM2: null,
    currentDensityMaM2: null,
    codRemovalPercent: null,
    treatmentRate: "",
    sourceLocator: "Kondrotaitė-Intė et al. (2025), DOI 10.3390/microorganisms13081938",
    use: "Feature evidence",
    qualityFlag: "Open-circuit voltage is not loaded voltage. Mediator and electrode modification make this a materials benchmark, not a direct operating recipe.",
  },
  {
    conditionId: "BV-LIT-008-PSEUDOMONAS",
    paperRecord: "BV-LIT-008",
    sourceFile: "Public full text; no local PDF",
    evidenceKind: "Benchmark only",
    access: "Public",
    microbe: "Pseudomonas aeruginosa",
    strainOrCommunity: "PA14, PAO1 and KRP1",
    anode: "Bioelectrochemical test; details retained in source paper",
    cathode: "Not comparable to MFC rows here",
    reactor: "Oxygen-limited bioelectrochemical cultures",
    anodeVolumeMl: null,
    membrane: "Not comparable",
    substrate: "Glucose, 2,3-butanediol or ethanol",
    substrateConcentrationG_L: null,
    salinityG_L: null,
    conductivityMsCm: null,
    temperatureC: null,
    ph: null,
    externalResistanceOhm: null,
    voltageV: null,
    voltageUncertaintyV: null,
    openCircuitVoltageV: null,
    powerDensityMwM2: null,
    powerDensityUncertaintyMwM2: null,
    currentDensityMaM2: 0.019,
    codRemovalPercent: null,
    treatmentRate: "30-35 mM substrate range",
    sourceLocator: "Bosire, Blank & Rosenbaum (2016), DOI 10.1128/AEM.01342-16",
    use: "Feature evidence",
    qualityFlag: "Supports strain and substrate features; current is reported in uA/cm2 and is not directly comparable to the MFC power-density rows.",
  },
  {
    conditionId: "BV-LIT-012-MFC-1000",
    paperRecord: "BV-LIT-012",
    sourceFile: "COD removal.pdf",
    evidenceKind: "Primary experiment",
    access: "Public",
    microbe: "Electroactive wastewater biofilm",
    strainOrCommunity: "Established electrochemically active biofilm; urban wastewater community",
    anode: "Graphite felt, 40 cm2",
    cathode: "Pt air cathode; 10-12.5 cm2 depending on comparison",
    reactor: "Air-cathode double chamber; 120 mL anode comparison",
    anodeVolumeMl: 120,
    membrane: "Not used in air-cathode comparison",
    substrate: "Urban wastewater",
    substrateConcentrationG_L: null,
    salinityG_L: null,
    conductivityMsCm: null,
    temperatureC: 20,
    ph: null,
    externalResistanceOhm: 1000,
    voltageV: null,
    voltageUncertaintyV: null,
    openCircuitVoltageV: null,
    powerDensityMwM2: null,
    powerDensityUncertaintyMwM2: null,
    currentDensityMaM2: null,
    codRemovalPercent: 50,
    treatmentRate: "Initial COD 290-330 mg/L; approx. 35% after background subtraction",
    sourceLocator: "COD removal.pdf, pp. 7-8; final comparison",
    use: "Treatment benchmark",
    qualityFlag: "Power-producing condition; the paper emphasizes that treatment and harvestable power are different objectives.",
  },
  {
    conditionId: "BV-LIT-012-SHORT",
    paperRecord: "BV-LIT-012",
    sourceFile: "COD removal.pdf",
    evidenceKind: "Primary experiment",
    access: "Public",
    microbe: "Electroactive wastewater biofilm",
    strainOrCommunity: "Established electrochemically active biofilm; urban wastewater community",
    anode: "Graphite felt, 40 cm2",
    cathode: "Pt air cathode; short circuit",
    reactor: "Air-cathode double chamber; 120 mL anode comparison",
    anodeVolumeMl: 120,
    membrane: "Not used in air-cathode comparison",
    substrate: "Urban wastewater",
    substrateConcentrationG_L: null,
    salinityG_L: null,
    conductivityMsCm: null,
    temperatureC: 20,
    ph: null,
    externalResistanceOhm: 0,
    voltageV: null,
    voltageUncertaintyV: null,
    openCircuitVoltageV: null,
    powerDensityMwM2: null,
    powerDensityUncertaintyMwM2: null,
    currentDensityMaM2: null,
    codRemovalPercent: 72,
    treatmentRate: "Initial COD 290-330 mg/L; approx. 55% after background subtraction",
    sourceLocator: "COD removal.pdf, pp. 7-8; final comparison",
    use: "Treatment benchmark",
    qualityFlag: "Short-circuit operation gives up external harvestable power; do not present it as an electricity-producing optimum.",
  },
  {
    conditionId: "BV-LIT-012-MES",
    paperRecord: "BV-LIT-012",
    sourceFile: "COD removal.pdf",
    evidenceKind: "Primary experiment",
    access: "Public",
    microbe: "Electroactive wastewater biofilm",
    strainOrCommunity: "Established electrochemically active biofilm; urban wastewater community",
    anode: "Graphite felt, 40 cm2",
    cathode: "Pt cathode connected as microbial electrochemical snorkel",
    reactor: "MES comparison; 120 mL anode",
    anodeVolumeMl: 120,
    membrane: "Not used in MES comparison",
    substrate: "Urban wastewater",
    substrateConcentrationG_L: null,
    salinityG_L: null,
    conductivityMsCm: null,
    temperatureC: 20,
    ph: null,
    externalResistanceOhm: 0,
    voltageV: null,
    voltageUncertaintyV: null,
    openCircuitVoltageV: null,
    powerDensityMwM2: null,
    powerDensityUncertaintyMwM2: null,
    currentDensityMaM2: null,
    codRemovalPercent: 69,
    treatmentRate: "Initial COD 290-330 mg/L",
    sourceLocator: "COD removal.pdf, pp. 7-8; final comparison",
    use: "Treatment benchmark",
    qualityFlag: "MES is a treatment configuration and cannot provide external electrical power in the same sense as a loaded MFC.",
  },
  {
    conditionId: "BV-SUP-001-BIOCHAR",
    paperRecord: "BV-SUP-001",
    sourceFile: "PDF 7.pdf",
    evidenceKind: "Supporting experiment",
    access: "Public",
    microbe: "Pseudomonas aeruginosa plus endogenous waste microflora",
    strainOrCommunity: "ATCC 15692; endogenous acidogenic community",
    anode: "Carbon brush",
    cathode: "Pinus resinosa biochar cathode, effective area 7 cm2",
    reactor: "Single chamber air cathode; 26 mL",
    anodeVolumeMl: 26,
    membrane: "None",
    substrate: "Shredded vegetable/food residues in PBS; 0.5% glucose added",
    substrateConcentrationG_L: null,
    salinityG_L: null,
    conductivityMsCm: null,
    temperatureC: 25,
    ph: 6.6,
    externalResistanceOhm: 1000,
    voltageV: null,
    voltageUncertaintyV: null,
    openCircuitVoltageV: null,
    powerDensityMwM2: null,
    powerDensityUncertaintyMwM2: null,
    currentDensityMaM2: null,
    codRemovalPercent: null,
    treatmentRate: "15-day cycles; biochar cathode reused for 3 cycles",
    sourceLocator: "PDF 7, pp. 4-7; Fig. 7",
    use: "Context only",
    qualityFlag: "Reported PD/CD use a combined cathode-area and treated-biomass normalization (W m-2 kg-1), so values are not pooled with mW/m2 rows. Shows fouling and pH decline as time-dependent features.",
  },
];

export const auditSummary = {
  papersReviewed: 14,
  conditionRows: auditRows.length,
  primaryRows: auditRows.filter((row) => row.evidenceKind === "Primary experiment").length,
  publicRows: auditRows.filter((row) => row.access === "Public").length,
  privateRows: auditRows.filter((row) => row.access === "Private reviewed").length,
  calculatorBenchmarks: auditRows.filter((row) => row.use === "Calculator benchmark").length,
  flaggedRows: auditRows.filter((row) => row.qualityFlag.length > 0).length,
};
