export type PaperKind = "Review" | "Primary research" | "Supporting source";

export type PaperMetric = { label: string; value: string };

export type PaperRecord = {
  record: string;
  kind: PaperKind;
  year: number;
  authors: string;
  title: string;
  journal: string;
  citation: string;
  doi: string;
  url: string;
  focus: string;
  access: string;
  sourceStatus: string;
  summary: string;
  studyDesign: string;
  metrics: PaperMetric[];
  keyFindings: string[];
  relevance: string;
  caveat: string;
  sourcePages: string;
};

export const papers: PaperRecord[] = [
  {
    record: "BV-LIT-001",
    kind: "Review",
    year: 2023,
    authors: "Aniket Naha, Reetika Debroy, Dhrubjyoti Sharma, Maulin P. Shah & Soumitra Nath",
    title: "Microbial fuel cell: A state-of-the-art and revolutionizing technology for efficient energy recovery",
    journal: "Cleaner and Circular Bioeconomy 5 (2023), 100050",
    citation: "Naha, A. et al. (2023). Cleaner and Circular Bioeconomy, 5, 100050.",
    doi: "10.1016/j.clcb.2023.100050",
    url: "https://doi.org/10.1016/j.clcb.2023.100050",
    focus: "Architecture, operating factors and energy recovery",
    access: "Open-access article; CC BY-NC-ND",
    sourceStatus: "Full text reviewed from supplied PDF 10",
    summary: "A broad review of MFC working principles, components, reactor modifications and the physicochemical factors that shape output, with attention to scale-up and resource recovery.",
    studyDesign: "Narrative review covering reactor configurations, electrodes, membranes, microorganisms, substrates and operating conditions.",
    metrics: [
      { label: "Temperature window", value: "20–40 °C discussed" },
      { label: "Main bottleneck", value: "Low and unstable output" },
      { label: "Scale strategy", value: "Modular stacks" },
    ],
    keyFindings: [
      "pH, conductivity, electrode properties and membrane choice are tightly coupled to internal resistance and power output.",
      "Ceramic materials and modular stacks are presented as routes toward more affordable, scalable systems.",
      "Cost, material durability, resistance and operational instability remain central deployment barriers.",
    ],
    relevance: "Defines the operating variables and system components that BioVolt AI should record before it makes predictions.",
    caveat: "The values synthesize many different reactor types and should not be treated as one comparable experimental dataset.",
    sourcePages: "Supplied PDF 10; article pp. 1–9",
  },
  {
    record: "BV-LIT-002",
    kind: "Review",
    year: 2022,
    authors: "Jayesh M. Sonawane et al.",
    title: "Recent progress in microbial fuel cells using substrates from diverse sources",
    journal: "Heliyon 8 (2022), e12353",
    citation: "Sonawane, J. M. et al. (2022). Heliyon, 8, e12353.",
    doi: "10.1016/j.heliyon.2022.e12353",
    url: "https://doi.org/10.1016/j.heliyon.2022.e12353",
    focus: "Substrate classes, operating conditions and scale-up",
    access: "Open-access article; CC BY-NC-ND",
    sourceStatus: "Full text reviewed from supplied PDF 5",
    summary: "Reviews MFC performance with industrial, agricultural, domestic and pharmaceutical waste streams and explains how substrate composition, loading and operating conditions affect electricity generation and treatment.",
    studyDesign: "Literature synthesis of substrate-dependent performance from laboratory and pilot MFCs.",
    metrics: [
      { label: "85 L system", value: "≈0.12 W/m²; ≈80% COD" },
      { label: "260 L system", value: "≈15 mW/m²; ≈80% COD" },
      { label: "Reviewed record", value: "8.8 W/m²" },
    ],
    keyFindings: [
      "Waste composition determines both biodegradability and the electroactive community that develops at the anode.",
      "Reported pilot systems can retain meaningful COD removal while their power density falls well below the strongest laboratory results.",
      "The review notes that current generation can approach zero once residual COD becomes very low, around 50 mg/L in a cited study.",
    ],
    relevance: "Supports substrate concentration, substrate type and COD before/after treatment as required model features.",
    caveat: "The numerical benchmarks are results cited by the review, not a single experiment performed by its authors.",
    sourcePages: "Supplied PDF 5; article pp. 1–28",
  },
  {
    record: "BV-LIT-003",
    kind: "Review",
    year: 2022,
    authors: "Nabil K. Abd-Elrahman et al.",
    title: "Applications of Nanomaterials in Microbial Fuel Cells: A Review",
    journal: "Molecules 27 (2022), 7483",
    citation: "Abd-Elrahman, N. K. et al. (2022). Molecules, 27, 7483.",
    doi: "10.3390/molecules27217483",
    url: "https://doi.org/10.3390/molecules27217483",
    focus: "Nanostructured electrodes, catalysts and membranes",
    access: "Open-access article; CC BY",
    sourceStatus: "Full text reviewed from supplied PDF 4",
    summary: "Examines carbon and metal nanomaterials used to improve anodes, cathodes and proton-exchange membranes by increasing surface area, electron transfer, biofilm attachment and oxygen-reduction activity.",
    studyDesign: "Material-centred review of carbon nanotubes, nanofibres, graphene, activated carbon, metal nanoparticles and metal oxides.",
    metrics: [
      { label: "Material families", value: "Carbon, metal and oxide" },
      { label: "Primary target", value: "Electron transfer" },
      { label: "Secondary target", value: "ORR and ion transport" },
    ],
    keyFindings: [
      "Nanostructured anodes can create more electrochemically active area and stronger microbial attachment.",
      "Cathode modification targets oxygen-reduction kinetics and can reduce reliance on expensive platinum.",
      "Membrane additives may improve proton transport or limit oxygen crossover, but stability and cost must be evaluated.",
    ],
    relevance: "Provides a future materials branch for electrode optimization and explains why surface area alone is not enough to describe an electrode.",
    caveat: "Performance gains depend on fabrication method and reactor context; they are not directly transferable to the historical graphite-rod MFC.",
    sourcePages: "Supplied PDF 4; article pp. 1–28",
  },
  {
    record: "BV-LIT-004",
    kind: "Review",
    year: 2023,
    authors: "Hridoy Roy et al.",
    title: "Microbial Fuel Cell Construction Features and Application for Sustainable Wastewater Treatment",
    journal: "Membranes 13 (2023), 490",
    citation: "Roy, H. et al. (2023). Membranes, 13, 490.",
    doi: "10.3390/membranes13050490",
    url: "https://doi.org/10.3390/membranes13050490",
    focus: "Construction, membranes and wastewater treatment",
    access: "Open-access article; CC BY",
    sourceStatus: "Full text reviewed from supplied PDF 6",
    summary: "Connects reactor architecture and material selection to wastewater treatment performance, covering electrodes, membranes, microorganisms, substrates and scale-up limitations.",
    studyDesign: "Review of MFC construction features and applications across multiple wastewater types.",
    metrics: [
      { label: "Treatment role", value: "Organics and nutrients" },
      { label: "Scale barrier", value: "Internal resistance" },
      { label: "Operational risk", value: "Biofouling" },
    ],
    keyFindings: [
      "Low output, voltage instability, internal resistance and mass-transfer limits recur across scaled systems.",
      "Biofilm behaviour is beneficial at the anode but fouling of membranes and cathodes can reduce long-term performance.",
      "Cheaper catalysts, alternative membranes, improved electrodes and hybrid systems are prominent development routes.",
    ],
    relevance: "Informs the digital twin’s reactor, treatment and fouling-alert modules.",
    caveat: "Wastewater composition and reporting conventions vary across the reviewed studies, limiting direct comparison.",
    sourcePages: "Supplied PDF 6; article pp. 1–29",
  },
  {
    record: "BV-LIT-005",
    kind: "Review",
    year: 2025,
    authors: "Tikam Chand Dakal et al.",
    title: "New horizons in microbial fuel cell technology: applications, challenges, and prospects",
    journal: "Biotechnology for Biofuels and Bioproducts 18 (2025), 79",
    citation: "Dakal, T. C. et al. (2025). Biotechnology for Biofuels and Bioproducts, 18, 79.",
    doi: "10.1186/s13068-025-02649-y",
    url: "https://doi.org/10.1186/s13068-025-02649-y",
    focus: "Emerging materials, microbes, biosensors and scale-up",
    access: "Open-access article; CC BY-NC-ND",
    sourceStatus: "Full text reviewed from supplied PDF 9",
    summary: "Surveys recent advances in nanomaterials, microbial engineering, biomass pretreatment, wastewater treatment and biosensing while framing the scientific and economic obstacles to scale.",
    studyDesign: "Forward-looking review of MFC applications, technology improvements and research gaps.",
    metrics: [
      { label: "Key limitation", value: "Low power density" },
      { label: "Biological risk", value: "Biofouling" },
      { label: "Future direction", value: "Engineered biocatalysts" },
    ],
    keyFindings: [
      "Electron-transfer efficiency, material cost and long-term stability remain coupled engineering problems.",
      "Nanomaterials and engineered microorganisms are promising but require safety, durability and economic evaluation.",
      "MFC biosensors can convert changes in microbial activity into useful environmental signals.",
    ],
    relevance: "Supports the platform roadmap from a monitoring dashboard toward interpretable prediction and biosensing.",
    caveat: "Many emerging approaches remain laboratory demonstrations and should be labelled by technology-readiness level.",
    sourcePages: "Supplied PDF 9; article pp. 1–22",
  },
  {
    record: "BV-LIT-006",
    kind: "Review",
    year: 2025,
    authors: "Ripel Chakma et al.",
    title: "Recent Applications, Challenges, and Future Prospects of Microbial Fuel Cells: A Review",
    journal: "Global Challenges 9 (2025), 2500004",
    citation: "Chakma, R. et al. (2025). Global Challenges, 9, 2500004.",
    doi: "10.1002/gch2.202500004",
    url: "https://doi.org/10.1002/gch2.202500004",
    focus: "Application benchmarks, challenges and future prospects",
    access: "Open-access article; CC BY",
    sourceStatus: "Full text reviewed from supplied PDF 8",
    summary: "Reviews wastewater treatment, biohydrogen, hazardous-waste remediation, electricity generation, robotics and biosensing, then compares performance limitations and future research paths.",
    studyDesign: "Application-led literature review with reported performance ranges from prior studies.",
    metrics: [
      { label: "Reviewed power", value: "2.44–3.31 W/m²" },
      { label: "Reviewed COD removal", value: "Up to 93.7%" },
      { label: "Reviewed CE", value: "Up to 55.6%" },
    ],
    keyFindings: [
      "The review reports up to 70% total-organic-carbon removal and up to 98% antibiotic removal in selected source studies.",
      "MFC applications extend beyond power generation to sensing, robotics and resource recovery.",
      "Cost, start-up time, system complexity and scale-up remain major barriers.",
    ],
    relevance: "Supplies literature benchmarks for contextual comparison, provided the platform preserves each study’s reactor and normalization basis.",
    caveat: "The displayed maxima come from different cited studies and must never be presented as a unified achievable target.",
    sourcePages: "Supplied PDF 8; article pp. 1–26",
  },
  {
    record: "BV-LIT-007",
    kind: "Primary research",
    year: 2025,
    authors: "Teresė Kondrotaitė-Intė, Antanas Zinovičius, Domas Pirštelis & Inga Morkvėnaitė",
    title: "Enhancing Electron Transfer Efficiency in Microbial Fuel Cells Through Gold Nanoparticle Modification of Saccharomyces cerevisiae",
    journal: "Microorganisms 13 (2025), 1938",
    citation: "Kondrotaitė-Intė, T. et al. (2025). Microorganisms, 13, 1938.",
    doi: "10.3390/microorganisms13081938",
    url: "https://doi.org/10.3390/microorganisms13081938",
    focus: "Gold nanoparticles and yeast electron transfer",
    access: "Open-access article; publisher and PubMed Central",
    sourceStatus: "Verified from the public full text; no local PDF supplied",
    summary: "Tests whether gold nanoparticles and polypyrrole improve electron transfer from Saccharomyces cerevisiae on graphite electrodes using electrochemical imaging and MFC measurements.",
    studyDesign: "Graphite-electrode yeast systems with Au nanoparticles, polypyrrole or both; glucose and ferricyanide mediator; cyclic voltammetry, SECM and two-electrode power tests.",
    metrics: [
      { label: "Sc:Au power", value: "22.8 mW/m²" },
      { label: "Yeast control", value: "5.7 mW/m²" },
      { label: "Sc:Au OCP", value: "455 mV" },
    ],
    keyFindings: [
      "Gold-modified yeast produced about four times the maximum power density of the yeast-only system.",
      "Sc:PPy reached 12.4 mW/m², while the combined Sc:PPy:Au treatment reached 7.4 mW/m².",
      "Median SECM currents were 2.57 nA for Sc:Au, 0.82 nA for Sc:PPy, 1.74 nA for Sc:PPy:Au and about 1.85 nA for yeast alone.",
    ],
    relevance: "Shows how surface modification and microbial state can become explicit electrode-level features in later BioVolt AI models.",
    caveat: "A laboratory mediator system with yeast is not directly comparable to mediator-free wastewater MFCs.",
    sourcePages: "Publisher full text and PubMed Central record",
  },
  {
    record: "BV-LIT-008",
    kind: "Primary research",
    year: 2016,
    authors: "Erick M. Bosire, Lars M. Blank & Miriam A. Rosenbaum",
    title: "Strain- and Substrate-Dependent Redox Mediator and Electricity Production by Pseudomonas aeruginosa",
    journal: "Applied and Environmental Microbiology 82 (2016), 5026–5038",
    citation: "Bosire, E. M., Blank, L. M. & Rosenbaum, M. A. (2016). Applied and Environmental Microbiology, 82, 5026–5038.",
    doi: "10.1128/AEM.01342-16",
    url: "https://doi.org/10.1128/AEM.01342-16",
    focus: "Pseudomonas strain, substrate and phenazine mediation",
    access: "Public full text through PubMed Central",
    sourceStatus: "Verified from public full text; no local PDF supplied",
    summary: "Compares three P. aeruginosa strains on three substrates to show that electricity and phenazine production depend on both organism and carbon source.",
    studyDesign: "PA14, PAO1 and KRP1 grown with glucose, 2,3-butanediol or ethanol under oxygen-limited bioelectrochemical conditions; predominantly triplicate experiments.",
    metrics: [
      { label: "Best current", value: "≈19 µA/cm²" },
      { label: "PCA in KRP1", value: "≈150 µg/mL" },
      { label: "Substrate range", value: "30–35 mM" },
    ],
    keyFindings: [
      "KRP1 with glucose gave the strongest reported current and phenazine-1-carboxylic-acid accumulation.",
      "PAO1 showed comparatively low bioelectrochemical activity under the tested conditions.",
      "Strain identity and substrate cannot be treated as interchangeable metadata.",
    ],
    relevance: "Directly motivates recording strain and substrate identity beside every Pseudomonas growth or MFC measurement.",
    caveat: "Most conditions were triplicate, but one condition was duplicated; transfer to another reactor requires validation.",
    sourcePages: "Public full text; article pp. 5026–5038",
  },
  {
    record: "BV-LIT-009",
    kind: "Primary research",
    year: 2017,
    authors: "Naeem Ali et al.",
    title: "Characterization of the Electric Current Generation Potential of Pseudomonas aeruginosa Using Glucose, Fructose, and Sucrose in Double Chamber Microbial Fuel Cell",
    journal: "Iranian Journal of Biotechnology 15 (2017), e1608",
    citation: "Ali, N. et al. (2017). Iranian Journal of Biotechnology, 15(4), e1608.",
    doi: "10.15171/ijb.1608",
    url: "https://doi.org/10.15171/ijb.1608",
    focus: "Pseudomonas substrate response in a double-chamber MFC",
    access: "Open-access article; CC BY-NC",
    sourceStatus: "Full text reviewed from supplied PDF 1",
    summary: "Compares glucose, fructose and sucrose as carbon sources for P. aeruginosa in a double-chamber MFC and reports voltage, normalized power, COD removal and biofilm observations.",
    studyDesign: "Two 500 mL bottles; 300 mL working volume; Nafion 115 membrane (25 cm²); 3 × 5 cm carbon-cloth electrodes with Pt cathode; 100 Ω operation; 21-day biofilm; 1–5 g/L sugars; duplicate batch tests.",
    metrics: [
      { label: "Glucose polarisation", value: "213 mW/m²" },
      { label: "Glucose at 100 Ω", value: "202 mV; 136 mW/m²" },
      { label: "Glucose COD", value: "88.5% at 3 g/L" },
    ],
    keyFindings: [
      "Glucose at 3 g/L produced the strongest output and the densest observed biofilm.",
      "Fructose at 3 g/L produced 33 mV and 3.6 mW/m² at 100 Ω; its polarization maximum was 6.84 mW/m² at 2.2 kΩ.",
      "COD removal at 5 g/L glucose reached 91% in the reported table; sucrose removal was lower, around 54.2% in the highlighted condition.",
    ],
    relevance: "Provides a clear substrate-response template for future experiment comparison and model features.",
    caveat: "The sucrose power values reported in the text and normalized polarization results are internally inconsistent, so both context and normalization must be retained.",
    sourcePages: "Supplied PDF 1; article pp. 1–8",
  },
  {
    record: "BV-LIT-010",
    kind: "Primary research",
    year: 2018,
    authors: "Ankisha Vijay, Prakash C. Ghosh & Suparna Mukherji",
    title: "Halophilic starch degrading bacteria isolated from Sambhar Lake, India, as potential anode catalyst in microbial fuel cell: A promising process for saline water treatment",
    journal: "Bioresource Technology 256 (2018), 391–398",
    citation: "Vijay, A., Ghosh, P. C. & Mukherji, S. (2018). Bioresource Technology, 256, 391–398.",
    doi: "10.1016/j.biortech.2018.02.044",
    url: "https://doi.org/10.1016/j.biortech.2018.02.044",
    focus: "Sambhar Lake halophiles, salinity and starch degradation",
    access: "Publisher-controlled article; redistribution licence not confirmed",
    sourceStatus: "PDF 11 reviewed privately; file deliberately not published",
    summary: "Isolates starch-degrading halophiles from Sambhar Lake and tests saline, starch-fed MFC performance across four NaCl concentrations with a nitrate-reducing cathode.",
    studyDesign: "Dual 100 mL chambers; Nafion 117; graphite-felt cathode; stainless-steel-mesh anode; 100 Ω; 37 °C; seven five-day cycles; 12 g/L starch; 500–3000 mM NaCl.",
    metrics: [
      { label: "Peak power", value: "207.05 ± 5 mW/m²" },
      { label: "Power optimum", value: "1000 mM NaCl" },
      { label: "Max amylase", value: "2.26 ± 0.20 IU/mL" },
    ],
    keyFindings: [
      "Power density at 500, 1000, 2000 and 3000 mM NaCl was 71.06, 207.05, 106.25 and 48.3 mW/m², respectively.",
      "Starch-removal rate rose from 1.045 to 3.2 kg/m³·d across the salinity series even as power fell at the highest salinity.",
      "Five isolates were assigned to Bacillus, Staphylococcus and Virgibacillus groups with reported 99% sequence identity and accessions MG050739–MG050743.",
    ],
    relevance: "The closest literature analogue to the college study because it combines Sambhar Lake halophiles, salinity, starch degradation and a double-chamber MFC.",
    caveat: "The article file is not hosted on BioVolt AI. Only an original summary, bibliographic metadata and selected reported measurements are shown.",
    sourcePages: "Supplied PDF 11; article pp. 391–398",
  },
  {
    record: "BV-LIT-011",
    kind: "Primary research",
    year: 2023,
    authors: "Ankisha Vijay, Prakash C. Ghosh & Suparna Mukherji",
    title: "Power Generation by Halophilic Bacteria and Assessment of the Effect of Salinity on Performance of a Denitrifying Microbial Fuel Cell",
    journal: "Energies 16 (2023), 877",
    citation: "Vijay, A., Ghosh, P. C. & Mukherji, S. (2023). Energies, 16, 877.",
    doi: "10.3390/en16020877",
    url: "https://doi.org/10.3390/en16020877",
    focus: "Halophile salinity response and denitrifying cathode",
    access: "Open-access article; CC BY",
    sourceStatus: "Full text reviewed from supplied PDF 2",
    summary: "Tests how increasing salinity changes power generation, organic removal, nitrate reduction, coulombic efficiency and electrode resistance in a halophile-inoculated denitrifying MFC.",
    studyDesign: "Dual 100 mL acrylic chambers; Nafion 117; carbon-felt cathode; stainless-steel-mesh anode; 100 Ω; pH 7; sodium acetate; 20 or 40 g/L NaCl; Arabian Sea inoculum; 37 °C; seven four-day fed-batch cycles; duplicate reactors.",
    metrics: [
      { label: "Power at 20 g/L", value: "96.77 ± 3 mW/m²" },
      { label: "Power at 40 g/L", value: "162.09 ± 3 mW/m²" },
      { label: "COD at 40 g/L", value: "83 ± 4%" },
    ],
    keyFindings: [
      "Voltage at 100 Ω increased from 240 ± 8 mV to 374 ± 7 mV when salinity rose from 20 to 40 g/L NaCl.",
      "COD removal increased from 76 ± 3.8% to 83 ± 4%, while nitrate removal increased from 80 ± 3% to 89 ± 3.2%.",
      "Coulombic efficiency increased from 12 ± 0.06% to 14 ± 0.08%, and charge-transfer resistance decreased from 20 to 16 Ω.",
    ],
    relevance: "Supplies directly comparable salinity, treatment and electrochemical fields for a future halophile model.",
    caveat: "Only two salinity levels and duplicate reactors were tested, so the apparent positive response should not be extrapolated outside that range.",
    sourcePages: "Supplied PDF 2; article pp. 1–16",
  },
  {
    record: "BV-SUP-001",
    kind: "Supporting source",
    year: 2021,
    authors: "Rosa Anna Nastro et al.",
    title: "Use of Biochar-Based Cathodes and Increase in the Electron Flow by Pseudomonas aeruginosa to Improve Waste Treatment in Microbial Fuel Cells",
    journal: "Processes 9 (2021), 1941",
    citation: "Nastro, R. A. et al. (2021). Processes, 9, 1941.",
    doi: "10.3390/pr9111941",
    url: "https://doi.org/10.3390/pr9111941",
    focus: "Biochar cathodes, Pseudomonas and vegetable-residue treatment",
    access: "Open-access article; CC BY",
    sourceStatus: "Full text reviewed from supplied PDF 7",
    summary: "Evaluates P. aeruginosa as an electron-flow enhancer and compares a reusable biochar air cathode with a higher-performing composite cathode during vegetable-residue treatment.",
    studyDesign: "26 mL single-chamber MFC; carbon-brush anode; 7 cm² biochar or nickel/activated-carbon/PTFE air cathode; 30% solid/liquid vegetable residue; 15-day cycles; P. aeruginosa ATCC 15692.",
    metrics: [
      { label: "Pseudomonas effect", value: "≈16.5× power increase" },
      { label: "Cycle length", value: "15 days" },
      { label: "Biochar reuse", value: "3 cycles" },
    ],
    keyFindings: [
      "P. aeruginosa substantially increased electron flow under the reported conditions.",
      "The composite cathode delivered higher initial output but fouled after about ten days and was associated with a pH decline.",
      "The biochar cathode was reused for three cycles and maintained a near-neutral pH more effectively.",
    ],
    relevance: "Supports later fouling alerts and shows why peak output and durability should be modelled as separate objectives.",
    caveat: "The article uses an unusual dual power normalization, W·m⁻²·kg⁻¹, so its values should not be compared directly with conventional W/m² records.",
    sourcePages: "Supplied PDF 7; article pp. 1–14",
  },
  {
    record: "BV-SUP-002",
    kind: "Supporting source",
    year: 2022,
    authors: "Deepalaxmi Rathakrishnan & Arun Kumar Gopalan",
    title: "Isolation and characterization of halophilic isolates from Indian salterns and their screening for production of hydrolytic enzymes",
    journal: "Environmental Challenges 6 (2022), 100426",
    citation: "Rathakrishnan, D. & Gopalan, A. K. (2022). Environmental Challenges, 6, 100426.",
    doi: "10.1016/j.envc.2021.100426",
    url: "https://doi.org/10.1016/j.envc.2021.100426",
    focus: "Halophile isolation and hydrolytic-enzyme screening",
    access: "Open-access publisher article",
    sourceStatus: "Supplied PDF 3 was a security page; metadata and abstract verified at the publisher",
    summary: "Screens a large collection of Indian-saltern isolates for salt tolerance, morphology and production of amylase, lipase, protease and cellulase.",
    studyDesign: "A total of 1,127 isolates were screened and 28 were selected for characterization and extracellular-enzyme assays.",
    metrics: [
      { label: "Initial isolates", value: "1,127" },
      { label: "Characterized", value: "28" },
      { label: "Protease range", value: "144.27–201.25 U/mg" },
    ],
    keyFindings: [
      "Most selected isolates were Gram-positive, with representatives assigned to Staphylococcus, Stenotrophomonas, Bacillus, Pseudomonas, Enterobacter, Ochrobactrum and Oceanobacillus groups.",
      "Six isolates showed the strongest reported protease activities; comparatively few isolates were cellulolytic.",
      "The work demonstrates that morphology alone cannot establish enzyme capability or taxonomic identity.",
    ],
    relevance: "Provides a supporting framework for halophile isolation, biochemical screening and follow-up molecular identification.",
    caveat: "The supplied HTML did not contain the article full text, and publisher highlights conflict at species level; no disputed species claim is reproduced here.",
    sourcePages: "Publisher metadata and abstract for article 100426",
  },
];
